// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeEntiry;

namespace PracticeEntiry.Migrations
{
    [DbContext(typeof(DtbaseContext))]
    [Migration("20211107115706_Added")]
    partial class Added
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PracticeEntiry.Models.Countries", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("PracticeEntiry.Models.Medals", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Medals");
                });

            modelBuilder.Entity("PracticeEntiry.Models.PartMedals", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MedalID")
                        .HasColumnType("int");

                    b.Property<int?>("MedalsID")
                        .HasColumnType("int");

                    b.Property<int>("PartID")
                        .HasColumnType("int");

                    b.Property<int?>("PartipicantsID")
                        .HasColumnType("int");

                    b.Property<int>("SportID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MedalsID");

                    b.HasIndex("PartipicantsID");

                    b.HasIndex("SportID");

                    b.ToTable("PartMedals");
                });

            modelBuilder.Entity("PracticeEntiry.Models.Partipicants", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.ToTable("Partipicants");
                });

            modelBuilder.Entity("PracticeEntiry.Models.Sports", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("PracticeEntiry.Models.PartMedals", b =>
                {
                    b.HasOne("PracticeEntiry.Models.Medals", "Medals")
                        .WithMany("PartMedals")
                        .HasForeignKey("MedalsID");

                    b.HasOne("PracticeEntiry.Models.Partipicants", "Partipicants")
                        .WithMany()
                        .HasForeignKey("PartipicantsID");

                    b.HasOne("PracticeEntiry.Models.Sports", "Sport")
                        .WithMany("Partipicants")
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medals");

                    b.Navigation("Partipicants");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("PracticeEntiry.Models.Partipicants", b =>
                {
                    b.HasOne("PracticeEntiry.Models.Countries", "Country")
                        .WithMany("Partipicants")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PracticeEntiry.Models.Countries", b =>
                {
                    b.Navigation("Partipicants");
                });

            modelBuilder.Entity("PracticeEntiry.Models.Medals", b =>
                {
                    b.Navigation("PartMedals");
                });

            modelBuilder.Entity("PracticeEntiry.Models.Sports", b =>
                {
                    b.Navigation("Partipicants");
                });
#pragma warning restore 612, 618
        }
    }
}
